# Temporary as I need to override the Netlify build settings for the Gatsby site
[build]
  publish = "/dist"


[[redirects]]
  from = "/contribute"
  to = "/get-involved"
  status = 301

[[redirects]]
  from = "/components/popup.research.explainer"
  to = "/components/popover.research.explainer"
  status = 301
